import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import StoreProvider from "@/store/StoreProvider";
import { Provider } from "react-redux";
import theme from "../theme";
import "react-toastify/dist/ReactToastify.css";
import "../assets/styles/index.scss";
import SideBar from "@/components/common/sideBar";
import { ToastContainer } from "react-toastify";
import store from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <ThemeProvider theme={theme}>
        <html lang="en">
          <body className={inter.className}>
            <SideBar />
            <AppRouterCacheProvider>
              {children}
              <ToastContainer
                position="bottom-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
              />
            </AppRouterCacheProvider>
          </body>
        </html>
      </ThemeProvider>
    </StoreProvider>
  );
}
